#!/usr/bin/env python3
"""Extract the two migration-078 identity resolvers VERBATIM into resolvers_078.sql.

WHY EXTRACT RATHER THAN LOAD 078. Migration 078 also creates invitation_resume_tokens,
invitation_resume_rate and resume_rotation_operations, and its claim functions reach into
invitation_deliveries (049) and the suppression rules. None of that is reachable from a profiles
INSERT. Loading it whole would put a large, unrelated surface into this harness where an unrelated
breakage could look like a migration-100 failure.

Only two objects matter here, and may_provision_profile calls both:
    public.lookup_auth_identity(text)
    public.lookup_waitlist_identity(text)

They are copied BYTE-FOR-BYTE. This file never edits, reformats or simplifies a body — the whole
point is that the harness measures the production definition, not a convenient restatement of it.
lib/__tests__/phase4a2-provisioning-boundary.test.ts asserts the round trip: every extracted body
must still appear verbatim in 078.

Same extraction rule as supabase/tests/phase3/extract.py: anchor on the literal
`CREATE OR REPLACE FUNCTION public.<name>(` and take the LAST such definition, never a textual
mention of the name elsewhere in the file.

    python3 supabase/tests/phase4a2/extract_resolvers.py
"""
from pathlib import Path
import sys

SOURCE = Path("supabase/migrations/078_invitation_resume_tokens.sql")
TARGET = Path("supabase/tests/phase4a2/resolvers_078.sql")

# name -> (must appear in the body, so a mislabelled extraction cannot pass silently)
WANTED = {
    "lookup_auth_identity": "FROM auth.users u",
    "lookup_waitlist_identity": "FROM public.waitlist w",
}

HEADER = """-- GENERATED by supabase/tests/phase4a2/extract_resolvers.py — DO NOT EDIT BY HAND.
--
-- The two migration-078 identity resolvers, copied verbatim. may_provision_profile (migration 100)
-- calls both, so the harness has to measure the real definitions rather than a restatement.
-- Regenerate with:  python3 supabase/tests/phase4a2/extract_resolvers.py
"""


def extract(sql: str, name: str, marker: str) -> str:
    anchor = f"CREATE OR REPLACE FUNCTION public.{name}("
    start = sql.rfind(anchor)
    if start < 0:
        sys.exit(f"extract: no definition of {name} in {SOURCE}")

    # Bodies in 078 are dollar-quoted with $fn$. Find the tag this definition opens with, then the
    # matching close, then the statement terminator.
    tag_start = sql.index("$", sql.index("AS ", start))
    tag_end = sql.index("$", tag_start + 1) + 1
    tag = sql[tag_start:tag_end]
    close = sql.index(tag, tag_end) + len(tag)
    end = sql.index(";", close) + 1

    body = sql[start:end]
    if marker not in body:
        sys.exit(f"extract: {name} body is missing its identity marker {marker!r} — wrong slice")
    for other in WANTED:
        if other != name and f"FUNCTION public.{other}(" in body:
            sys.exit(f"extract: {name} slice swallowed {other} — wrong slice")
    return body


def main() -> None:
    sql = SOURCE.read_text()
    parts = [HEADER]
    for name, marker in WANTED.items():
        parts.append(f"\n-- ── public.{name} — verbatim from {SOURCE.name} ──\n")
        parts.append(extract(sql, name, marker))
        parts.append("\n")
    TARGET.write_text("".join(parts))
    print(f"wrote {TARGET} ({len(''.join(parts))} bytes, {len(WANTED)} functions)")


if __name__ == "__main__":
    main()
