-- GENERATED by supabase/tests/phase4a2/extract_resolvers.py — DO NOT EDIT BY HAND.
--
-- The two migration-078 identity resolvers, copied verbatim. may_provision_profile (migration 100)
-- calls both, so the harness has to measure the real definitions rather than a restatement.
-- Regenerate with:  python3 supabase/tests/phase4a2/extract_resolvers.py

-- ── public.lookup_auth_identity — verbatim from 078_invitation_resume_tokens.sql ──
CREATE OR REPLACE FUNCTION public.lookup_auth_identity(p_email text)
  RETURNS TABLE (identity_count integer, auth_user_id uuid, last_sign_in_at timestamptz)
  LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = ''
AS $fn$
DECLARE
  v_norm text := pg_catalog.lower(pg_catalog.btrim(coalesce(p_email, '')));
BEGIN
  IF v_norm = '' THEN
    RETURN QUERY SELECT 0, NULL::uuid, NULL::timestamptz; RETURN;
  END IF;

  RETURN QUERY
  SELECT (pg_catalog.count(*))::integer,
         -- Meaningful ONLY when the count is 1. A caller that ignores the count and uses this uuid
         -- anyway would be acting on an ambiguous identity, so it is NULL in that case by design.
         CASE WHEN pg_catalog.count(*) = 1 THEN (pg_catalog.array_agg(u.id))[1] END,
         pg_catalog.max(u.last_sign_in_at)
  FROM auth.users u
  WHERE pg_catalog.lower(pg_catalog.btrim(u.email)) = v_norm;
END;
$fn$;

-- ── public.lookup_waitlist_identity — verbatim from 078_invitation_resume_tokens.sql ──
CREATE OR REPLACE FUNCTION public.lookup_waitlist_identity(p_email text)
  RETURNS TABLE (
    total_rows        integer,
    invited_count     integer,
    invited_id        uuid,
    has_revoked       boolean,
    has_declined      boolean,
    has_other_status  boolean
  )
  LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = ''
AS $fn$
DECLARE
  v_norm text := pg_catalog.lower(pg_catalog.btrim(coalesce(p_email, '')));
BEGIN
  IF v_norm = '' THEN
    RETURN QUERY SELECT 0, 0, NULL::uuid, false, false, false; RETURN;
  END IF;

  RETURN QUERY
  SELECT (pg_catalog.count(*))::integer,
         (pg_catalog.count(*) FILTER (WHERE w.status = 'invited'))::integer,
         -- Meaningful ONLY when invited_count = 1; a caller that ignores the count and uses this id
         -- anyway would be acting on an ambiguous invitation, so it is NULL otherwise by design.
         CASE WHEN pg_catalog.count(*) FILTER (WHERE w.status = 'invited') = 1
              THEN (pg_catalog.array_agg(w.id) FILTER (WHERE w.status = 'invited'))[1] END,
         pg_catalog.bool_or(w.status = 'revoked'),
         pg_catalog.bool_or(w.status = 'declined'),
         pg_catalog.bool_or(w.status NOT IN ('invited', 'revoked', 'declined'))
  FROM public.waitlist w
  WHERE pg_catalog.lower(pg_catalog.btrim(w.email)) = v_norm;
END;
$fn$;
